// src/components/index/Timeline.jsx
import React from 'react';
import classnames from 'classnames';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { layout } from '../../public/data/timeline.json';

const TimelineTag = data => (
  <div>
    <header className="timeline-header">
      <span className={classnames('tag', data.item.color, data.item.size)}>
        { data.item.text }
      </span>
    </header>
    <style jsx>{`
      .tag.icon-bitcoin {
        background-color: #ff9900;
        color: #ffffff;
      }
    `}
    </style>
  </div>
);

const TimelineItem = (data) => {
  const isFuture = Date.now() < (new Date(data.item.startDate)).getTime();

  return (
    <div>
      <div className={classnames('timeline-item', data.item.color)}>
        <div className={classnames('timeline-marker', 'is-icon', 'has-text-white', data.item.color)}>
          <FontAwesomeIcon icon={data.item.icon} />
        </div>
        <div className="timeline-content">
          <p className="heading">
            <strong>{ data.item.company }</strong> - { data.item.role }
            <br />
            { isFuture ? <i><strong>FUTURE</strong> ({ data.item.startDate })</i> : (
              <i>
                { data.item.startDate } - { data.item.endDate
                  ? <span>{ data.item.endDate }</span> : <span><strong>Now</strong></span>
                }
              </i>
            )}
          </p>
        </div>
      </div>
      <style jsx>{`
        .timeline-item.icon-bitcoin::before {
          background-color: #ff9900;
        }
        .timeline-item .timeline-marker.icon-bitcoin.is-icon {
          border-color: #ff9900;
          background-color: #ff9900;
          color: #ffffff;
        }
      `}
      </style>
    </div>
  );
};

export default class extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      year: (new Date()).getFullYear(),
      layout,
    };
  }

  render() {
    const { year, layout: timeline } = this.state;
    return (
      <div className="timeline">
        <header className="timeline-header">
          <span className="tag is-medium is-primary">{ year + 1 }</span>
        </header>
        { timeline.map((item) => {
          if (item.type === 'tag') {
            return <TimelineTag key={item.text || item.company} item={item} />;
          }
          return <TimelineItem key={item.text || item.company} item={item} />;
        })}
      </div>
    );
  }
}

// src/components/resume/Timeline.vue
<template>
  <div class="timeline is-rtl">
    <header class="timeline-header">
      <span class="tag is-medium is-primary">{{ this.year + 1 }}</span>
    </header>
    <div class="timeline-item is-success">
      <div class="timeline-marker is-success is-icon has-text-white">
        <font-awesome-icon icon="bicycle" />
      </div>
      <div class="timeline-content">
        <p class="heading"><strong>Lime</strong> - Software Engineering Intern</p>
        <p>
          FUTURE
        </p>
      </div>
    </div>
    <header class="timeline-header">
      <span class="tag is-primary">2019</span>
    </header>
    <div class="timeline-item is-danger">
      <div class="timeline-marker is-danger is-icon has-text-white">
        <font-awesome-icon icon="shopping-bag" />
      </div>
      <div class="timeline-content">
        <p class="heading">
          <strong>Ebates/Rakuten</strong> - Software Engineering Intern
        </p>
        <p>
          June to September 2015
        </p>
      </div>
    </div>
    <header class="timeline-header">
      <span class="tag is-primary">2018</span>
    </header>
    <div class="timeline-item is-warning">
      <div class="timeline-marker is-warning is-icon">
        <font-awesome-icon icon="shipping-fast" />
      </div>
      <div class="timeline-content">
        <p class="heading">
          <strong>Roambee</strong> - Software Engineering Intern
        </p>
        <p>
          July to August 2015
        </p>
      </div>
    </div>
    <header class="timeline-header">
      <span class="tag is-primary">2016</span>
    </header>
    <div class="timeline-item color-bitcoin">
      <div class="timeline-marker color-bitcoin is-icon">
        <font-awesome-icon :icon="['fab', 'bitcoin']" />
      </div>
      <div class="timeline-content">
        <p class="heading"><strong>Card for Coin</strong> - Software Engineering Intern</p>
        <p>
          June to August 2015
        </p>
      </div>
    </div>
    <header class="timeline-header">
      <span class="tag is-medium is-primary">2015</span>
    </header>
  </div>
</template>

<script>
export default {
  data() {
    return {
      year: (new Date()).getFullYear(),
    };
  },
};
</script>

<style lang="scss" scoped>
// Bitcoin
.timeline .timeline-item.color-bitcoin::before {
  background-color: #ff9900;

}
.timeline .timeline-item .timeline-marker.color-bitcoin.is-icon {
  border-color: #ff9900;
  background-color: #ff9900;
  color: white;
}
</style>
