// src/pages/index.vue
<template>
  <div>
    <section class="hero is-medium is-black">
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="header title">
            Hi, I'm Manthan.
          </h1>
          <h2 class="header subtitle is-6 has-text-weight-light">
            You can find me online <a href="https://keybase.io/nahtnam" class="has-text-weight-bold is-lowercase" target="_blank" rel="noopener noreferrer">@nahtnam</a>.
          </h2>
        </div>
      </div>
    </section>
    <section id="first-section" class="section">
      <div class="container">
        <div class="columns">
          <div class="column no-pad-bottom is-three-quarters">
            <div class="has-text-centered">
              <h1 class="header title is-4">
                About Me
              </h1>
              <AboutMe />
            </div>
            <hr>
            <div class="has-text-centered">
              <h1 class="header title is-4">
                Statistics
              </h1>
              <Statistics />
            </div>
            <hr>
            <div class="has-text-centered">
              <h1 class="header title is-4">
                Projects
              </h1>
              <Projects />
            </div>
            <hr>
            <div class="has-text-centered">
              <h1 class="header title is-4">
                Social Media
              </h1>
              <Social />
            </div>
            <hr>
            <div class="has-text-centered">
              <h1 class="header title is-4">
                Shout-Outs
              </h1>
              <Quote />
            </div>
          </div>
          <div class="column no-pad-bottom is-one-quarter">
            <hr class="is-hidden-tablet">
            <div>
              <h1 class="header title is-4 has-text-centered">
                Work
              </h1>
              <Timeline />
            </div>
            <hr>
            <div class="has-text-centered">
              <h1 class="header title is-4">
                Experience
              </h1>
              <Languages />
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
import AboutMe from '@/components/home/AboutMe.vue';
import Statistics from '@/components/home/Statistics.vue';
import Projects from '@/components/home/Projects.vue';
import Social from '@/components/home/Social.vue';
import Quote from '@/components/home/Quote.vue';
import Timeline from '@/components/home/Timeline.vue';
import Languages from '@/components/home/Languages.vue';

export default {
  components: {
    AboutMe,
    Statistics,
    Projects,
    Social,
    Quote,
    Timeline,
    Languages,
  },
};
</script>

// src/pages/index.jsx
import React from 'react';

import AboutMe from '../components/index/AboutMe';
import Projects from '../components/index/Projects';
import Social from '../components/index/Social';
import Quote from '../components/index/Quote';

import Timeline from '../components/index/Timeline';

export default () => (
  <div>
    <section className="hero is-medium is-black">
      <div className="hero-body">
        <div className="container has-text-centered">
          <h1 className="header title">
            { 'Hi, I\'m Manthan.' }
          </h1>
          <h2 className="header subtitle is-6 has-text-weight-light">
            You can find me online <a href="https://keybase.io/nahtnam" className="has-text-weight-bold is-lowercase" target="_blank" rel="noopener noreferrer">@nahtnam</a>.
          </h2>
        </div>
      </div>
    </section>
    <section id="first-section" className="section">
      <div className="container">
        <div className="columns">
          <div className="column no-pad-bottom is-three-quarters">
            <div className="has-text-centered">
              <h1 className="header title is-4">
                About Me
              </h1>
              <AboutMe />
            </div>
            <hr />
            <div className="has-text-centered">
              <h1 className="header title is-4">
                Statistics
              </h1>
              {/* <Statistics /> */}
            </div>
            <hr />
            <div className="has-text-centered">
              <h1 className="header title is-4">
                Projects
              </h1>
              <Projects />
            </div>
            <hr />
            <div className="has-text-centered">
              <h1 className="header title is-4">
                Social Media
              </h1>
              <Social />
            </div>
            <hr />
            <div className="has-text-centered">
              <h1 className="header title is-4">
                Shout-Outs
              </h1>
              <Quote />
            </div>
          </div>
          <div className="column no-pad-bottom is-one-quarter">
            <hr className="is-hidden-tablet" />
            <div>
              <h1 className="header title is-4 has-text-centered">
                Work
              </h1>
              <Timeline />
            </div>
            <hr />
            <div className="has-text-centered">
              <h1 className="header title is-4">
                Experience
              </h1>
              {/* <Languages /> */}
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
);
