// src/components/index/AboutMe.jsx
import React from 'react';

export default () => (
  <div>
    <nav className="level">
      <div className="level-item has-text-centered">
        <figure className="image is-128x128">
          <img src="/nahtnam.png" alt="nahtnam" className="is-rounded has-text-centered" />
        </figure>
      </div>
    </nav>
    <div className="content is-large">
      { 'I\'m a student, full-stack developer, researcher, gamer, and crypto-currency enthusiast.' }
    </div>
  </div>
);

// src/components/home/AboutMe.vue
<template>
  <div>
    <nav class="level">
      <div class="level-item has-text-centered">
        <figure class="image is-128x128">
          <img src="~/assets/images/nahtnam.png" alt="nahtnam" class="is-rounded has-text-centered">
        </figure>
      </div>
    </nav>
    <div class="content is-large">
      I'm a student, full-stack developer, researcher, gamer, and crypto-currency enthusiast.
    </div>
  </div>
</template>
