// src/components/index/Projects.jsx
import React from 'react';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { projects } from '../../static/data/projects.json';
import color from '../../utils/projects/tag-color';

const showcase = projects.filter(p => p.showcase);

const ProjectCard = data => (
  <div className="column">
    <div className="card">
      <header className="card-header">
        <p className="card-header-title is-centered">
          { data.project.name }
        </p>
      </header>
      <div className="card-content">
        <div className="content">
          <p>{ data.project.description }</p>
          <div className="tags">
            { data.project.stack.concat().sort().map(tag => (
              <span key={tag} className="tag is-black" style={{ backgroundColor: color(tag) }}>{ tag }</span>
            )) }
          </div>
        </div>
      </div>
      <footer className="card-footer">
        {data.project.url ? (
          <a href={data.project.url} target="_blank" rel="noopener noreferrer" className="card-footer-item">
            <span className="icon">
              <FontAwesomeIcon icon="eye" />
            </span>
            View
          </a>
        ) : null}
        { data.project.github ? (
          <a href={data.project.github} target="_blank" rel="noopener noreferrer" className="card-footer-item">
            <span className="icon">
              <FontAwesomeIcon icon={['fab', 'github']} />
            </span>
            Source
          </a>
        ) : null}
      </footer>
      <style jsx>
        {`
          .card-footer-item .icon {
            padding-right: 1em;
          }
        `}
      </style>
    </div>
  </div>
);

export default () => (
  <div>
    <div className="columns">
      { showcase.map(project => <ProjectCard key={project.name} project={project} />)}
    </div>
    <Link href="/projects">
      <a className="button is-fullwidth is-info is-outlined">
        <span className="icon">
          <FontAwesomeIcon icon="code" />
        </span>
        <span>View All Projects</span>
      </a>
    </Link>
  </div>
);

// src/components/home/Projects.vue
<template>
  <div>
    <div class="columns">
      <div class="column" v-for="project in projects" :key="project.name">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title is-centered">
              {{ project.name }}
            </p>
          </header>
          <div class="card-content">
            <div class="content">
              <p>{{ project.description }}</p>
              <div class="tags">
                <span class="tag is-black" v-for="tag in project.stack.concat().sort()" :key="tag" :style="{ 'background-color': color(tag) }">{{ tag }}</span>
              </div>
            </div>
          </div>
          <footer class="card-footer">
            <a :href="project.url" v-if="project.url" target="_blank" rel="noopener noreferrer" class="card-footer-item">
              <span class="icon">
                <font-awesome-icon icon="eye" />
              </span>
              View
            </a>
            <a :href="project.github" v-if="project.github" target="_blank" rel="noopener noreferrer" class="card-footer-item">
              <span class="icon">
                <font-awesome-icon :icon="['fab', 'github']" />
              </span>
              Source
            </a>
          </footer>
        </div>
      </div>
    </div>
    <a class="button is-fullwidth is-info is-outlined">
      <span class="icon">
        <font-awesome-icon icon="code" />
      </span>
      <span>View All Projects</span>
    </a>
  </div>
</template>

<script>
import { projects } from '@/static/home/projects.json';
import color from '@/utils/projects/tag-color';

export default {
  data() {
    return {
      projects: projects.filter(obj => obj.showcase),
    };
  },

  methods: {
    color,
  },
};
</script>

<style lang="scss" scoped>
.card-footer-item .icon {
  padding-right: 1em;
}
</style>
