// src/components/index/Timeline.jsx
import React from 'react';
import classnames from 'classnames';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import { layout } from '../../static/data/timeline.json';

const TimelineTag = data => (
  <div>
    <header className="timeline-header">
      <span className={classnames('tag', data.item.color, data.item.size)}>
        { data.item.text }
      </span>
    </header>
    <style jsx>{`
      .tag.icon-bitcoin {
        background-color: #ff9900;
        color: #ffffff;
      }
    `}</style>
  </div>
);

const TimelineItem = data => (
  <div>
    <div className={classnames('timeline-item', data.item.color)}>
      <div className={classnames('timeline-marker', 'is-icon', 'has-text-white', data.item.color)}>
        <FontAwesomeIcon icon={data.item.icon} />
      </div>
      <div className="timeline-content">
        <p className="heading">
          <strong>{ data.item.company }</strong> - { data.item.role }
          <br />
          { Date.now() < (new Date(data.item.startDate)).getTime() ? <i><strong>FUTURE</strong> ({ data.item.startDate })</i> : (
            <i>
              { data.item.startDate } - { data.item.endDate ? <span>{ data.item.endDate }</span> : <span><strong>Now</strong></span>}
            </i>
          )}
        </p>
      </div>
    </div>
    <style jsx>{`
      .timeline .timeline-item.icon-bitcoin::before {
        background-color: #ff9900;
      }
      .timeline .timeline-item .timeline-marker.icon-bitcoin.is-icon {
        border-color: #ff9900;
        background-color: #ff9900;
        color: #ffffff;
      }
      .tag.icon-bitcoin {
        background-color: #ff9900;
        color: #ffffff;
      }
    `}</style>
  </div>
);

export default class extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      year: (new Date()).getFullYear(),
      layout,
    }
  }

  render() {
    const { year, layout } = this.state;
    return (
      <div className="timeline">
        <header className="timeline-header">
          <span className="tag is-medium is-primary">{ year + 1 }</span>
        </header>
        { layout.map((item) => {
          if (item.type === 'tag') {
            return <TimelineTag key={item.text || item.company} item={item} />;
          }
          return <TimelineItem key={item.text || item.company} item={item} />
        })}
      </div>
    );
  }
}

// src/components/home/Timeline.vue
<template>
  <div class="timeline">
    <header class="timeline-header">
      <span class="tag is-medium is-primary">{{ year + 1 }}</span>
    </header>
    <div v-for="item in layout" :key="item.text || item.company">
      <header class="timeline-header" v-if="item.type === 'tag'">
        <span class="tag" :class="[item.color, item.size].join(' ')">{{ item.text }}</span>
      </header>
      <div class="timeline-item" :class="item.color" v-else-if="item.type === 'item'">
        <div class="timeline-marker is-icon has-text-white" :class="item.color">
          <font-awesome-icon :icon="item.icon" />
        </div>
        <div class="timeline-content">
          <p class="heading">
            <strong>{{ item.company }}</strong> - {{ item.role }}
            <br>
            <i v-if="Date.now() < (new Date(item.startDate)).getTime()"><strong>FUTURE</strong> ({{ item.startDate }})</i>
            <i v-else>
              {{ item.startDate }} -
              <span v-if="item.endDate">{{ item.endDate }}</span>
              <span v-else><strong>Now</strong></span>
            </i>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { layout } from '@/static/timeline.json';

export default {
  data() {
    return {
      year: (new Date()).getFullYear(),
      layout,
    };
  },
};
</script>

<style lang="scss" scoped>
// Bitcoin
.timeline .timeline-item.color-bitcoin::before {
  background-color: #ff9900;

}
.timeline .timeline-item .timeline-marker.color-bitcoin.is-icon {
  border-color: #ff9900;
  background-color: #ff9900;
  color: #ffffff;
}
.tag:not(body).color-bitcoin {
  background-color: #ff9900;
  color: #ffffff;
}
</style>
