// apps/web/src/routes/-components/footer/index.tsx
import { appName } from "@repo/config/app";

export function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="footer footer-center border-base-200 border-t bg-base-100 px-8 py-6 text-base-content/60">
      <aside>
        <p className="text-sm">
          &copy; {year} {appName}
        </p>
      </aside>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <div>
    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          &copy; {{ year }} nahtnam.
        </p>
      </div>
    </footer>
  </div>
</template>

<script>
export default {
  name: 'Footer',
  data() {
    return {
      year: (new Date()).getFullYear(),
    };
  },
};
</script>

<style lang="scss" scoped>
.footer {
  padding: 3rem 1.5rem;
}
</style>
