// src/components/Navigation.jsx
import React from 'react';
import Link from 'next/link';
import classnames from 'classnames';

export default class extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      active: false,
    };

    this.toggleMenu = this.toggleMenu.bind(this);
    this.closeMenu = this.closeMenu.bind(this);
  }

  toggleMenu() {
    this.setState(prevState => ({
      active: !prevState.active,
    }));
  }

  closeMenu() {
    this.setState({
      active: false,
    });
  }

  render() {
    const { active } = this.state;
    return (
      <nav id="main-navbar" className="navbar is-black is-transparent">
        <div className="container">
          <div className="navbar-brand">
            <Link href="/">
              <a className="navbar-item has-text-weight-bold">
                <span className="is-size-5">nahtnam</span>
              </a>
            </Link>

            <div className={classnames('navbar-burger', 'burger', { 'is-active': active })} role="navigation" onClick={this.toggleMenu}>
              <span />
              <span />
              <span />
            </div>
          </div>

          <div className={classnames('navbar-menu', 'header', { 'is-active': active })}>
            <div className="navbar-end">
              <Link href="/">
                <a className="navbar-item" role="navigation" onClick={this.closeMenu}>
                  Home
                </a>
              </Link>
              <Link href="/projects">
                <a className="navbar-item" role="navigation" onClick={this.closeMenu}>
                  Projects
                </a>
              </Link>
              <Link href="/photos">
                <a className="navbar-item" role="navigation" onClick={this.closeMenu}>
                  Photos
                </a>
              </Link>
              <Link href="/resume">
                <a className="navbar-item" role="navigation" onClick={this.closeMenu}>
                  Résumé
                </a>
              </Link>
            </div>
          </div>
        </div>
      </nav>
    );
  }
}

// src/components/Navigation.vue
<template>
  <nav id="main-navbar" class="navbar is-black is-transparent">
    <div class="container">
      <div class="navbar-brand">
        <router-link class="navbar-item has-text-weight-bold" to="/">
          <span class="is-size-5">nahtnam</span>
        </router-link>

        <div class="navbar-burger burger" :class="{ 'is-active': active }" @click="toggleMenu">
          <span />
          <span />
          <span />
        </div>
      </div>

      <div class="navbar-menu header" :class="{ 'is-active': active }">
        <div class="navbar-end">
          <nuxt-link
            to="/"
            class="navbar-item"
            active-class="is-active"
            exact
            @click.native="closeMenu"
          >
            Home
          </nuxt-link>
          <nuxt-link
            to="/projects"
            class="navbar-item"
            active-class="is-active"
            @click.native="closeMenu"
          >
            Projects
          </nuxt-link>
          <nuxt-link
            to="/photos"
            class="navbar-item"
            active-class="is-active"
            @click.native="closeMenu"
          >
            Photos
          </nuxt-link>
          <a href="/resume" class="navbar-item">Résumé</a>
        </div>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navigation',
  data() {
    return {
      active: false,
    };
  },
  methods: {
    closeMenu() {
      this.active = false;
    },
    toggleMenu() {
      this.active = !this.active;
    },
  },
};
</script>
