// src/components/home/Languages.vue
<template>
  <div>
    <div class="columns no-margin-bottom is-vcentered" v-for="language in languages" :key="language.name">
      <div class="column is-one-third header is-size-7" v-html="language.name"></div>
      <div class="column">
        <progress class="progress is-large" :class="getColor(language.experience)" :value="language.experience" max="100">
          <div class="progress-bar">
            {{ language.experience }}%
          </div>
        </progress>
      </div>
    </div>
  </div>
</template>

<script>
import orderBy from 'lodash/orderby';
import { languages } from '@/static/languages.json';

export default {
  data() {
    return {
      languages: orderBy(languages, ['experience'], ['desc']).map((lang) => {
        const dup = Object.assign(lang, {});
        dup.name = dup.name.split('/').join('/&#8203');
        return dup;
      }),
    };
  },

  methods: {
    getColor(experience) {
      if (experience < 33) {
        return 'is-danger';
      }
      if (experience < 66) {
        return 'is-info';
      }
      return 'is-success';
    },
  },
};
</script>

// src/components/index/Languages.jsx
import React from 'react';
import orderBy from 'lodash.orderby';
import classnames from 'classnames';

import { languages } from '../../static/data/languages.json';

const skills = orderBy(languages, ['experience'], ['desc']).map((lang) => {
  const dup = Object.assign(lang, {});
  dup.name = dup.name.split('/').join('/&#8203');
  return dup;
});

const getColor = (experience) => {
  if (experience < 33) {
    return 'is-danger';
  }
  if (experience < 66) {
    return 'is-info';
  }
  return 'is-success';
};

export default () => (
  <div>
    { skills.map(skill => (
      <div key={skill.name} className="columns no-margin-bottom is-vcentered">
        <div className="column is-one-third header is-size-7" dangerouslySetInnerHTML={{ __html: skill.name }} />
        <div className="column">
          <progress className={classnames('progress', 'is-large', getColor(skill.experience))} value={skill.experience} max="100">
            <div className="progress-bar">
              { skill.experience }%
            </div>
          </progress>
        </div>
      </div>
    )) }
  </div>
);
