// src/views/Projects.vue
<template>
  <div class="projects">
    <section class="hero is-primary">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            Projects
          </h1>
          <h2 class="subtitle">
            I work on side-projects in different frameworks and programming languages whenever I find the time.
          </h2>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">
        <div class="columns content" v-for="group in this.projects" :key="`group-${group[0].name}`">
          <div class="column is-one-third" v-for="project in group" :key="project.name">
            <div class="card">
              <div class="card-content">
                <p class="title no-pad-bottom">
                  {{ project.name }}
                </p>
                <p class="is-size-5">
                  {{ project.description }}
                </p>
              </div>
              <footer class="card-footer">
                <a :href="project.url" v-if="project.url" target="_blank" class="card-footer-item">View Project</a>
                <a :href="project.github" v-if="project.github" target="_blank" class="card-footer-item">View on GitHub</a>
              </footer>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
import { projects } from '@/../public/projects.json';

export default {
  name: 'home',
  data() {
    return {
      projects: [],
    };
  },

  created() {
    this.projects = projects.map((e, i) => ((i % 3 === 0) ? projects.slice(i, i + 3) : null)).filter(e => e);
  },
};
</script>

// src/components/index/Projects.jsx
import React from 'react';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { projects } from '../../public/data/projects.json';
import color from '../../utils/projects/tag-color';

const showcase = projects.filter((p) => p.showcase);

const ProjectCard = (data) => (
  <div className="column">
    <div className="card">
      <header className="card-header">
        <p className="card-header-title is-centered">
          { data.project.name }
        </p>
      </header>
      <div className="card-content">
        <div className="content">
          <p>{ data.project.description }</p>
          <div className="tags">
            { data.project.stack.concat().sort().map((tag) => (
              <span key={tag} className="tag is-black" style={{ backgroundColor: color(tag) }}>{ tag }</span>
            )) }
          </div>
        </div>
      </div>
      <footer className="card-footer">
        {data.project.url ? (
          <a href={data.project.url} target="_blank" rel="noopener noreferrer" className="card-footer-item">
            <span className="icon">
              <FontAwesomeIcon icon="eye" />
            </span>
            View
          </a>
        ) : null}
        { data.project.github ? (
          <a href={data.project.github} target="_blank" rel="noopener noreferrer" className="card-footer-item">
            <span className="icon">
              <FontAwesomeIcon icon={['fab', 'github']} />
            </span>
            Source
          </a>
        ) : null}
      </footer>
      <style jsx>
        {`
          .card-footer-item .icon {
            padding-right: 1em;
          }
        `}
      </style>
    </div>
  </div>
);

export default () => (
  <div>
    <div className="columns">
      { showcase.map((project) => <ProjectCard key={project.name} project={project} />)}
    </div>
    <div className="columns">
      <div className="column is-one-third is-offset-one-third">
        <Link href="/projects">
          <a className="button is-fullwidth is-info is-outlined">
            <span className="icon">
              <FontAwesomeIcon icon="code" />
            </span>
            <span>View All Projects</span>
          </a>
        </Link>
      </div>
    </div>
  </div>
);
