// src/components/home/Statistics.vue
<template>
  <div>
    <div class="columns">
      <div class="column">
        <div>
          <p class="title is-marginless" :class="{ 'is-loading': contributions.loading }">
            {{ contributions.text }}+
          </p>
          <p class="heading">
            Contributions
          </p>
        </div>
      </div>
      <div class="column">
        <div>
          <p class="title is-marginless" :class="{ 'is-loading': age.loading }">
            {{ age.text }}
          </p>
          <p class="heading">
            Years Old
          </p>
        </div>
      </div>
      <div class="column">
        <div>
          <p class="title is-marginless" :class="{ 'is-loading': repos.loading }">
            {{ repos.text }}+
          </p>
          <p class="heading">
            Repos
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      age: {
        text: '---',
        loading: true,
      },
      contributions: {
        text: '---',
        loading: true,
      },
      repos: {
        text: '---',
        loading: true,
      },
    };
  },

  async created() {
    try {
      this.getAge();
      this.ageInterval = setInterval(this.getAge, 1000);
    } catch (_) {
      // do nothing
    }
    this.age.loading = false;

    await Promise.all([this.getContributions(), this.getRepos()]);
  },

  beforeDestroy() {
    if (!this.ageInterval) {
      return;
    }
    clearInterval(this.ageInterval);
  },

  methods: {
    async getRepos() {
      try {
        const users = ['nahtnam', 'j-tester', 'ludicrousxyz', 'srvrjs'];
        const reqsArr = users.map(usr => fetch(`https://api.github.com/users/${usr}`));
        const reqs = await Promise.all(reqsArr);
        const res = await Promise.all(reqs.map(r => r.json()));
        const reposCount = res.reduce((acc, val) => acc + val.public_repos, 0);
        this.repos.text = reposCount;
      } catch (_) {
        // do nothing
      }
      this.repos.loading = false;
    },

    async getContributions() {
      try {
        const req = await fetch('https://github-contributions-api.now.sh/v1/nahtnam');
        const { years } = await req.json();
        const total = years.reduce((acc, val) => acc + val.total, 0);
        this.contributions.text = total.toLocaleString();
      } catch (_) {
        // do nothing
      }
      this.contributions.loading = false;
    },

    getAge(birthday = 'October 10, 1999') {
      const diff = Date.now() - (new Date(birthday).getTime());
      const age = diff / (1000 * 60 * 60 * 24 * 365);
      this.age.text = age.toFixed(7);
    },
  },
};
</script>

// src/components/index/Statistics.jsx
/* global fetch */

import React from 'react';
import classnames from 'classnames';

export default class extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      age: {
        text: '---',
        loading: true,
      },
      contributions: {
        text: '---',
        loading: true,
      },
      repos: {
        text: '---',
        loading: true,
      },
    };

    this.getAge = this.getAge.bind(this);
  }

  componentDidMount() {
    this.getAge();
    const ageInterval = setInterval(this.getAge, 1000);
    this.setState(prevState => ({
      age: {
        ...prevState.age,
        loading: false,
      },
      ageInterval,
    }));

    this.getRepos();
    this.getContributions();
  }

  componentWillUnmount() {
    const { ageInterval } = this.state;
    clearInterval(ageInterval);
  }

  async getRepos() {
    try {
      const users = ['nahtnam', 'j-tester', 'ludicrousxyz', 'srvrjs'];
      const reqsArr = users.map(usr => fetch(`https://api.github.com/users/${usr}`));
      const reqs = await Promise.all(reqsArr);
      const res = await Promise.all(reqs.map(r => r.json()));
      const reposCount = res.reduce((acc, val) => acc + val.public_repos, 0);
      this.setState({
        repos: {
          text: reposCount,
          loading: false,
        },
      });
    } catch (_) {
      this.setState({
        repos: {
          loading: false,
        },
      });
    }
  }

  async getContributions() {
    try {
      const req = await fetch('https://github-contributions-api.now.sh/v1/nahtnam');
      const { years } = await req.json();
      const total = years.reduce((acc, val) => acc + val.total, 0);
      this.setState({
        contributions: {
          text: total.toLocaleString(),
          loading: false,
        },
      });
    } catch (_) {
      this.setState({
        contributions: {
          loading: false,
        },
      });
    }
  }

  getAge(birthday = 'October 10, 1999') {
    const diff = Date.now() - (new Date(birthday).getTime());
    const age = diff / (1000 * 60 * 60 * 24 * 365);
    this.setState({
      age: {
        text: age.toFixed(7),
      },
    });
  }

  render() {
    const { contributions, age, repos } = this.state;
    return (
      <div>
        <div className="columns">
          <div className="column">
            <p className={classnames('title', 'is-marginless', { 'is-loading': contributions.loading })}>
              { contributions.text }+
            </p>
            <p className="heading">
              Contributions on GitHub
            </p>
          </div>
          <div className="column">
            <p className={classnames('title', 'is-marginless', { 'is-loading': age.loading })}>
              { age.text }
            </p>
            <p className="heading">
              Years Old
            </p>
          </div>
          <div className="column">
            <p className={classnames('title', 'is-marginless', { 'is-loading': repos.loading })}>
              { repos.text }+
            </p>
            <p className="heading">
              Repos Created
            </p>
          </div>
        </div>
      </div>
    );
  }
}
