// src/components/index/Timeline.vue
<template>
  <v-timeline align-top dense>
    <v-timeline-item color="pink" small v-for="item in layout" :key="item.type">
      <template v-slot:opposite>
        <i v-if="Date.now() < (new Date(item.startDate)).getTime()"><strong>FUTURE</strong> ({{ item.startDate }})</i>
        <i v-else>
          {{ item.startDate }} -
          <span v-if="item.endDate">{{ item.endDate }}</span>
          <span v-else><strong>Now</strong></span>
        </i>
      </template>
      <template v-slot:icon>
        <span>JL</span>
      </template>
      <v-layout pt-3>
        <v-flex>
          <strong>{{ item.company }}</strong>
          <div class="caption">{{ item.role }}</div>
        </v-flex>
      </v-layout>
    </v-timeline-item>
  </v-timeline>
</template>

<script>
import { layout } from '@/static/timeline.json';

export default {
  data() {
    return {
      year: (new Date()).getFullYear(),
      layout: layout.filter(x => x.type === 'item'),
    };
  },
};
</script>

// src/components/index/Timeline.jsx
import React from 'react';
import classnames from 'classnames';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import { layout } from '../../static/data/timeline.json';

const TimelineTag = data => (
  <div>
    <header className="timeline-header">
      <span className={classnames('tag', data.item.color, data.item.size)}>
        { data.item.text }
      </span>
    </header>
    <style jsx>{`
      .tag.icon-bitcoin {
        background-color: #ff9900;
        color: #ffffff;
      }
    `}</style>
  </div>
);

const TimelineItem = data => (
  <div>
    <div className={classnames('timeline-item', data.item.color)}>
      <div className={classnames('timeline-marker', 'is-icon', 'has-text-white', data.item.color)}>
        <FontAwesomeIcon icon={data.item.icon} />
      </div>
      <div className="timeline-content">
        <p className="heading">
          <strong>{ data.item.company }</strong> - { data.item.role }
          <br />
          { Date.now() < (new Date(data.item.startDate)).getTime() ? <i><strong>FUTURE</strong> ({ data.item.startDate })</i> : (
            <i>
              { data.item.startDate } - { data.item.endDate ? <span>{ data.item.endDate }</span> : <span><strong>Now</strong></span>}
            </i>
          )}
        </p>
      </div>
    </div>
    <style jsx>{`
      .timeline .timeline-item.icon-bitcoin::before {
        background-color: #ff9900;
      }
      .timeline .timeline-item .timeline-marker.icon-bitcoin.is-icon {
        border-color: #ff9900;
        background-color: #ff9900;
        color: #ffffff;
      }
      .tag.icon-bitcoin {
        background-color: #ff9900;
        color: #ffffff;
      }
    `}</style>
  </div>
);

export default class extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      year: (new Date()).getFullYear(),
      layout,
    }
  }

  render() {
    const { year, layout } = this.state;
    return (
      <div className="timeline">
        <header className="timeline-header">
          <span className="tag is-medium is-primary">{ year + 1 }</span>
        </header>
        { layout.map((item) => {
          if (item.type === 'tag') {
            return <TimelineTag key={item.text || item.company} item={item} />;
          }
          return <TimelineItem key={item.text || item.company} item={item} />
        })}
      </div>
    );
  }
}
